#!/bin/bash

dbpw=PW_FOR_DB_ROOT_USER_HERE

#Loops through every folder in the apache root directory
while read folder
do
        #Backups every folder in the apache directory to their folder in /backups
        tar -C /var/www/html/ -cpf /backups/$folder/"$folder.backup.$(date +%m-%d-%Y).tar" $folder

        #Backs up each database, zips it, then deletes the initial sql file
        mysqldump -p$dbpw $folder > /backups/$folder/"$folder.backup.$(date +%m-%d-%Y)".sql
        tar -cpf /backups/$folder/"$folder.backup.$(date +%m-%d-%Y).sql.tar" /backups/$folder/"$folder.backup.$(date +%m-%d-%Y)".sql
        rm -f /backups/$folder/"$folder.backup.$(date +%m-%d-%Y)".sql
done < <(ls -1d /var/www/html/*/ | cut -d '/' -f5)


#Cleanup! If a user has more than 4 files in their backup directory, anything older than 3 weeks will be deleted
#This way, even if users no longer have hosting, there will still be 2 complete backups of their files
while read folder
do
        num=$(ls /backups/$folder/ | wc -l)

        if [ $num -gt 4 ]; then
                find /backups/$folder -type f -mmin +30240 -delete
        fi

done < <(ls -1d /backups/* | cut -d '/' -f3)
